// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcD310Wtx5uHwnX2EYYNAvcCGRrfB_xXo',
    appId: '1:91828601681:web:4fec212ea7d7f308c34970',
    messagingSenderId: '91828601681',
    projectId: 'perpus-glo',
    authDomain: 'perpus-glo.firebaseapp.com',
    storageBucket: 'perpus-glo.firebasestorage.app',
    measurementId: 'G-LCY7J1480E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjzbfKetS77Ir7s0twEv774eE2FXTIY10',
    appId: '1:91828601681:android:66080079687ee20bc34970',
    messagingSenderId: '91828601681',
    projectId: 'perpus-glo',
    storageBucket: 'perpus-glo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYlM4REbwsGflq7OcWF8xfzB_OUqDlnK0',
    appId: '1:91828601681:ios:eb3d8cc107d27536c34970',
    messagingSenderId: '91828601681',
    projectId: 'perpus-glo',
    storageBucket: 'perpus-glo.firebasestorage.app',
    iosBundleId: 'com.mif.perpusGlo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYlM4REbwsGflq7OcWF8xfzB_OUqDlnK0',
    appId: '1:91828601681:ios:eb3d8cc107d27536c34970',
    messagingSenderId: '91828601681',
    projectId: 'perpus-glo',
    storageBucket: 'perpus-glo.firebasestorage.app',
    iosBundleId: 'com.mif.perpusGlo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcD310Wtx5uHwnX2EYYNAvcCGRrfB_xXo',
    appId: '1:91828601681:web:3a77d4f2a6108afec34970',
    messagingSenderId: '91828601681',
    projectId: 'perpus-glo',
    authDomain: 'perpus-glo.firebaseapp.com',
    storageBucket: 'perpus-glo.firebasestorage.app',
    measurementId: 'G-19LK6DQ4PM',
  );
}
