name: perpusglo
description: Aplikasi Peminjaman dan Pembayaran Buku Digital

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # 🔧 State Management
  flutter_riverpod: ^2.5.1

 # 🔥 Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.15.4
  firebase_messaging: ^14.9.0

  # 💬 Notifikasi
  awesome_notifications: ^0.10.1

  # 💰 Pembayaran (via link QR manual)
  url_launcher: ^6.2.6

  # 📦 Local Storage (opsional jika kamu perlu menyimpan setting/user data lokal)
  shared_preferences: ^2.2.2

  # 🎨 UI & UX
  google_fonts: ^6.2.1
  flutter_spinkit: ^5.2.0
  intl: ^0.20.0
  cached_network_image: ^3.3.1
  pull_to_refresh: ^2.0.0

  # ✅ Form & Validasi
  formz: ^0.6.1

  # 🔠 QR Scan (opsional jika scan QR ditambahkan)
  # qr_code_scanner: ^1.0.1
  mobile_scanner: ^3.5.1

  # 🔀 Routing (jika pakai GoRouter, opsional)
  go_router: ^13.2.2
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  #   - assets/icons/